### PR TITLE
Add the ability to require certain phrases to appear in the log files

### PR DESCRIPTION
**Pull request by eflumerf**

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I tested this with the insufficient disk space test, and I didn't see any complaints about missing required messages, so that was good.
However, I was quite confused by the fact that the required messages were also included in the ignored messages list.  
I was thinking that it might be possible to check whether a given line in the log file had a required string in it and then skip the existing checks.  My sense is that it would be nice if the ignored strings and the required strings in the test driver file could be distinct (non-overlapping).

**Comment by bieryAtFnal** [comment]
And, it would be nice to have positive confirmation somehow that the required strings were found, instead of relying on the absence of complaints about them not being found.

**Comment by eflumerf** [comment]
I think that in that case, we are expecting a certain set of errors, so for the logfile check to be correct we have to both ignore the errors (so that the "logfiles are error-free" check succeeds) *and* require their presence.

You can imagine a case where we are requiring some "success" Info message to be present where it would not also have to be in the ignored list.

I will look at adding to the report...

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
